- name: varaibles from files
  hosts: localhost
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
     msg: "course_name: {{COURSE}}, Course_duration: {{DURATION}}, name of institute: {{Institute}}"